apiVersion: v1
kind: BuildConfig
metadata:
  name: php
  labels:
    app: php70
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "php", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
  - type: GitHub
    github:
      secret: c23abb6b90a41f7169d98319a75e5b35
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
         node {
           stage('buildImage'){
             openshiftBuild(buildConfig: 'php', showBuildLogs: 'true')
           }
           stage('deployApplication'){
             openshiftDeploy(deploymentConfig: 'php')
           }
         }
